- name: configure backend 
  hosts: backend
  become: yes
  vars:
   login_host: backend.expensedevops.online
   login_password: ExpenseApp@1
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y
  - name: start and enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install required modules
    ansible.builtin.dnf: 
     name : "{{item}}"
     state: installed
    loop:
     - nodejs
     - mysql


