- name: configure backend 
  hosts: backend
  become: yes
  vars:
   login_host: backend.expensedevops.online
   login_password: ExpenseApp@1
  tasks:
  - name: disable node js
    ansible.builtin.command: dnf module disable nodejs -y
  - name: start and enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install required modules
    ansible.builtin.dnf: 
     name : "{{item}}"
     state: installed
    loop:
     - nodejs
     - mysql
  - name: expense user add
    ansible.builtin.user: 
     name: expense
  - name: makdir 
    ansible.builtin.file:
     path: /app
     state: directory
  - name: get code
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     dest: /tmp/backend.zip
  - name: unzip code
    ansible.builtin.unarchive:
     src: /tmp/backend.zip
     dest: /app
     remote_src: yes
  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: Copy backend service
    ansible.builtin.copy:
     src: backend.service
     dest: /etc/systemd/system/backend.service
  