- name : setup db
  hosts: db
  become: yes
  vars:
   login_host: db.expensedevops.online
  vars_prompt:
   - name: database_password
     prompt: please enter password
     private : no
  tasks:
   - name: install my sql server
     ansible.builtin.dnf:
      name : mysql-server
      state: latest

   - name: start and enable mysql server service
     ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

   - name: install dependencies
     ansible.builtin.pip:
       name : 
        - PyMySql
        - cryptography

       executable: pip3.9
   - name: check mysql server root password
     community.mysql.mysql_info:
       login_user: root
       login_password: {{database_password}}
       login_host: {{login_host}}
       filter: version
     ignore_errors: yes
     register: output

    - name: print output
      ansible.builtin.debug:
       msg: "{{output}}"


    
   